#! /bin/sh
sxhkd & bspc monitor eDP-1 -d 1 2 3 4 5  
bspc monitor DP-1 -d 6 7 8 9 
bspc monitor DP-2 -d 6 7 8 9 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a Chromium ='^2'
bspc rule -a slack desktop='^2'
bspc rule -a code-oss desktop='^3'
bspc rule -a Eclipse desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Spotify desktop='^5'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating 
bspc rule -a dolphin state=floating 
bspc rule -a app.App state=floating
bspc config focus_follows_pointer true 
setxkbmap eu
feh --bg-scale ~/Pictures/4kwall.jpg 
~/.config/polybar/launch.sh
compton
xidlehook --not-when-fullscreen --not-when-audio --timer 600 'systemctl suspend' ''
#touchpad
xinput set-prop 11 "libinput Tapping Enabled" 1
xinput set-prop 11 "libinput Natural Scrolling Enabled" 1
#fix java stuff
wmname LG3D
#keyrepeat
xset r rate 200 40
