#! /bin/sh

sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5  
bspc monitor DP-1 -d 6 7 8 9 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Slack desktop='^2'
bspc rule -a code-oss desktop='^3'
bspc rule -a Eclipse desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true 
setxkbmap no 
feh --bg-scale ~/Pictures/LightWaves.png 
~/.config/polybar/launch.sh
compton
